"""Enforce native/'s layering by its #includes (docs/native-port-plan.md).

- core/ includes no Qt and no <jni.h>, except under core/*/qt/ and
  core/*/android/ (device backends, split at the device boundary).
- Qt Widgets only under gui/ (data2g-gui); app/ (the station runtime both
  apps share) and apps/ stay Core/Network, so a mobile front end can reuse
  them. Widgets headers are known by the QtWidgets/ prefix or by name.
- generated files are only written by tools/gen_native_tables.py: each
  must still carry its header.

    python tools/check_layering.py   # exit 1 and list violations
"""

import re
import sys
from pathlib import Path

NATIVE = Path(__file__).resolve().parent.parent / "native"
INCLUDE = re.compile(r'^\s*#\s*include\s*[<"]([^>"]+)[>"]', re.M)
GENERATED = "// Generated by tools/gen_native_tables.py"
# QtWidgets' class headers likely to be reached for; QtWidgets/... catches the rest.
WIDGETS = re.compile(
    r"QtWidgets(/|$)|Q(Application|Widget|MainWindow|Dialog|DialogButtonBox|MessageBox|Label|PushButton"
    r"|ToolButton|AbstractButton|RadioButton|CheckBox|ComboBox|LineEdit|TextEdit|PlainTextEdit|SpinBox"
    r"|DoubleSpinBox|Slider|ProgressBar|GroupBox|Frame|Splitter|TabWidget|StackedWidget|ScrollArea"
    r"|BoxLayout|[HV]BoxLayout|GridLayout|FormLayout|Layout|TableWidget|TableView|TreeWidget|TreeView"
    r"|ListWidget|ListView|HeaderView|AbstractItemView|StatusBar|MenuBar|Menu|ToolBar|FileDialog"
    r"|SystemTrayIcon|SizePolicy|Style|StyleOption)$")


def main() -> int:
    bad = []
    for path in sorted((NATIVE / "core").rglob("*.[ch]pp")):
        rel = path.relative_to(NATIVE)
        text = path.read_text()
        for inc in INCLUDE.findall(text):
            if (inc == "jni.h" and "android" not in rel.parts
                    or re.match(r"Q[A-Za-z]", inc) and "qt" not in rel.parts):
                bad.append(f"{rel}: includes <{inc}> outside a device backend")
        if "generated" in rel.parts and not text.startswith(GENERATED):
            bad.append(f"{rel}: in core/generated/ but not generated")
    for path in sorted(NATIVE.rglob("*.[ch]pp")):
        rel = path.relative_to(NATIVE)
        if rel.parts[0] in ("gui", "build", "third_party") or rel.parts[0].startswith("build"):
            continue
        for inc in INCLUDE.findall(path.read_text()):
            if WIDGETS.match(inc):
                bad.append(f"{rel}: includes <{inc}> (Qt Widgets) outside gui/")
    for b in bad:
        print(b)
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
