"""Enforce native/'s layering by its #includes (docs/native-port-plan.md).

- core/ includes no Qt and no <jni.h>, except under core/*/qt/ and
  core/*/android/ (device backends, split at the device boundary).
- generated files are only written by tools/gen_native_tables.py: each
  must still carry its header.

    python tools/check_layering.py   # exit 1 and list violations
"""

import re
import sys
from pathlib import Path

NATIVE = Path(__file__).resolve().parent.parent / "native"
INCLUDE = re.compile(r'^\s*#\s*include\s*[<"]([^>"]+)[>"]', re.M)
GENERATED = "// Generated by tools/gen_native_tables.py"


def main() -> int:
    bad = []
    for path in sorted((NATIVE / "core").rglob("*.[ch]pp")):
        rel = path.relative_to(NATIVE)
        text = path.read_text()
        for inc in INCLUDE.findall(text):
            if (inc == "jni.h" and "android" not in rel.parts
                    or re.match(r"Q[A-Za-z]", inc) and "qt" not in rel.parts):
                bad.append(f"{rel}: includes <{inc}> outside a device backend")
        if "generated" in rel.parts and not text.startswith(GENERATED):
            bad.append(f"{rel}: in core/generated/ but not generated")
    for b in bad:
        print(b)
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
