"""Generate the native core's constants and frozen tables from the Python
reference (docs/native-port-plan.md, "What must be frozen, not ported").

    python tools/gen_native_tables.py           # (re)write native/core/generated/
    python tools/gen_native_tables.py --check   # exit 1 if any file is stale

Python is normative: these files are only ever regenerated, never edited.
Everything the C++ core needs at run time is compiled in, so a build has no
data files to find (Android stays possible).
"""

import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
OUT = ROOT / "native" / "core" / "generated"

for var in ("DATA2G_PREAMBLE_REPEATS",):
    if var in os.environ:
        sys.exit(f"{var} is set: the generated tables must hold the on-air defaults")

import numpy as np  # noqa: E402

from data2g import codes, config  # noqa: E402

HEADER = "// Generated by tools/gen_native_tables.py from {src}. Do not edit.\n"
# Globals that are not plain constants, or are emitted in another form.
SKIP = {"BANDS", "SUBMODES", "CLIP", "CLIP_OVERSHOOT_TABLE", "PREAMBLE_THRESHOLDS"}


def cxx(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return f'"{v}"'
    if isinstance(v, float):
        return repr(v)
    return str(v)


def array(name: str, values, ctype: str) -> str:
    return f"inline constexpr std::array<{ctype}, {len(values)}> {name} = {{{', '.join(cxx(v) for v in values)}}};\n"


def ctype_of(values) -> str:
    if all(isinstance(v, str) for v in values):
        return "std::string_view"
    return "double" if any(isinstance(v, float) for v in values) else "int"


def config_hpp() -> str:
    out = [HEADER.format(src="data2g/config.py"), "#pragma once\n\n#include <array>\n#include <span>\n",
           "#include <string_view>\n\nnamespace data2g::config {\n\n"]
    for name, v in vars(config).items():
        if not name.isupper() or name.startswith("_") or name in SKIP:
            continue
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            out.append(f"inline constexpr {'double' if isinstance(v, float) else 'int'} {name} = {cxx(v)};\n")
        elif isinstance(v, tuple) and v:
            out.append(array(name, v, ctype_of(v)))
        else:
            sys.exit(f"config.{name}: no C++ form for {type(v).__name__}; emit it or add it to SKIP")
    out.append(f"inline constexpr double PREAMBLE_THRESHOLD = {cxx(config.PREAMBLE_THRESHOLDS[config.PREAMBLE_REPEATS])};\n")

    out.append("\nstruct Band {\n    std::string_view name;\n    int k0, nc;\n    std::span<const int> pilot_num;\n"
               "    int header_syms, preamble_repeats;\n    double clip_headroom_db;\n"
               "    std::span<const double> clip_overshoot;\n    std::string_view sync_band;\n};\n\n")
    for b in config.BANDS.values():
        out.append(array(f"PILOT_{b.name}", b.pilot_num, "int"))
        out.append(array(f"CLIP_OVERSHOOT_{b.name}", b.clip_overshoot, "double"))
    out.append(f"\ninline constexpr std::array<Band, {len(config.BANDS)}> BANDS = {{{{\n")
    for b in config.BANDS.values():
        out.append(f'    {{"{b.name}", {b.k0}, {b.nc}, PILOT_{b.name}, {b.header_syms}, {b.preamble_repeats}, '
                   f'{cxx(float(b.clip_headroom_db))}, CLIP_OVERSHOOT_{b.name}, "{b.sync_band}"}},\n')
    out.append("}};\n\n")

    out.append("// Per submode: the spec plus what Python derives from it, so the two\n"
               "// cannot disagree about sizes.\nstruct Submode {\n    int index;\n    std::string_view name, code, constellation, band, sync_band;\n"
               "    int frames_per_cw, k, bits_per_cu, coded_bits, crc_bits, payload_bytes;\n"
               "    double headroom;\n    std::span<const double> ace;\n};\n\n")
    subs = list(config.SUBMODES.values())
    for i, s in enumerate(subs):
        if s.ace:
            out.append(array(f"ACE_{i}", tuple(float(a) for a in s.ace), "double"))
    out.append(f"\ninline constexpr std::array<Submode, {len(subs)}> SUBMODES = {{{{\n")
    for i, s in enumerate(subs):
        ace = f"ACE_{i}" if s.ace else "{}"
        out.append(f'    {{{s.index}, "{s.name}", "{s.code}", "{s.constellation}", "{s.band}", "{s.sync_band}", '
                   f"{s.frames_per_cw}, {s.k}, {s.bits_per_cu}, {s.coded_bits}, {codes.crc_bits(s)}, "
                   f"{codes.payload_bytes(s)}, {cxx(float(s.headroom))}, {ace}}},\n")
    out.append("}};\n\n}  // namespace data2g::config\n")
    return "".join(out)


def ints(values) -> str:
    return ",".join(str(int(v)) for v in values)


def format_cpp() -> str:
    """Every submode's frozen interleaver and polar info set (data2g/format)."""
    out = [HEADER.format(src="data2g/format/*.npz"), '#include "tables/tables.hpp"\n\n',
           "namespace data2g::tables {\nnamespace {\n\n"]
    rows = []
    for i, s in enumerate(config.SUBMODES.values()):
        f = codes.frozen(s)
        if f is None:
            sys.exit(f"{s.name}: no frozen format file matches its spec; run tools/freeze_format.py first")
        perm = f["perm"]
        assert perm.max() < 65536 and sorted(perm) == list(range(s.coded_bits))
        out.append(f"constexpr std::uint16_t perm_{i}[] = {{{ints(perm)}}};\n")
        info = f"std::span<const std::uint16_t>{{}}"
        if "info_pos" in f:
            out.append(f"constexpr std::uint16_t info_{i}[] = {{{ints(f['info_pos'])}}};\n")
            info = f"info_{i}"
        rows.append(f'    {{"{s.name}", perm_{i}, {info}}},\n')
    out.append("\n}  // namespace\n\n")
    out.append(f"const std::array<Format, {len(rows)}> FORMATS = {{{{\n{''.join(rows)}}}}};\n\n}}  // namespace data2g::tables\n")
    return "".join(out)


def polar_ga_cpp() -> str:
    """Polar info sets the live path designs at run time (GA density
    evolution at codes.POLAR_DESIGN_SNR_DB) because no frozen file holds
    one: the CPM control codewords. Keyed by (k, e)."""
    from data2g import cpm

    out = [HEADER.format(src="data2g/polar.py (codes.polar_code of cpm.CTL)"), '#include "tables/tables.hpp"\n\n',
           f"// Design SNR {cxx(float(codes.POLAR_DESIGN_SNR_DB))} dB.\n",
           "namespace data2g::tables {\nnamespace {\n\n"]
    rows, seen = [], set()
    for s in cpm.CTL.values():
        if s.code != "polar" or (s.k, s.coded_bits) in seen:
            continue
        code = codes.polar_code(s)
        assert code.frozen_override is None, f"{s.name} has a frozen info set; it doesn't belong here"
        seen.add((s.k, s.coded_bits))
        out.append(f"constexpr std::uint16_t ga_{len(rows)}[] = {{{ints(code.info_pos)}}};\n")
        rows.append(f"    {{{s.k}, {s.coded_bits}, ga_{len(rows)}}},\n")
    out.append(f"\nconstexpr PolarDesign designs[] = {{\n{''.join(rows)}}};\n\n}}  // namespace\n\n"
               "const std::span<const PolarDesign> POLAR_GA = designs;\n\n}  // namespace data2g::tables\n")
    return "".join(out)


FILES = {"config.hpp": config_hpp, "format.cpp": format_cpp, "polar_ga.cpp": polar_ga_cpp}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="compare, write nothing")
    args = ap.parse_args()
    stale = []
    for name, gen in FILES.items():
        path, text = OUT / name, gen()
        if args.check:
            if not path.exists() or path.read_bytes() != text.encode():
                stale.append(name)
        else:
            OUT.mkdir(parents=True, exist_ok=True)
            path.write_bytes(text.encode())
    if stale:
        sys.exit(f"stale: {', '.join(stale)} (run tools/gen_native_tables.py)")


if __name__ == "__main__":
    main()
