"""Generate the native core's constants and frozen tables from the Python
reference (docs/native-port-plan.md, "What must be frozen, not ported").

    python tools/gen_native_tables.py           # (re)write native/core/generated/
    python tools/gen_native_tables.py --check   # exit 1 if any file is stale

Python is normative: these files are only ever regenerated, never edited.
Everything the C++ core needs at run time is compiled in, so a build has no
data files to find (Android stays possible).
"""

import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
OUT = ROOT / "native" / "core" / "generated"

for var in ("DATA2G_PREAMBLE_REPEATS", "DATA2G_OUTCOME_MODEL"):
    if var in os.environ:
        sys.exit(f"{var} is set: the generated tables must hold the on-air defaults")

import numpy as np  # noqa: E402

from data2g import codes, config, constellation  # noqa: E402

HEADER = "// Generated by tools/gen_native_tables.py from {src}. Do not edit.\n"
# Globals that are not plain constants, or are emitted in another form.
SKIP = {"BANDS", "SUBMODES", "CLIP", "CLIP_OVERSHOOT_TABLE", "PREAMBLE_THRESHOLDS"}


def cxx(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return f'"{v}"'
    if isinstance(v, float):
        return repr(v)
    return str(v)


def array(name: str, values, ctype: str) -> str:
    return f"inline constexpr std::array<{ctype}, {len(values)}> {name} = {{{', '.join(cxx(v) for v in values)}}};\n"


def ctype_of(values) -> str:
    if all(isinstance(v, str) for v in values):
        return "std::string_view"
    return "double" if any(isinstance(v, float) for v in values) else "int"


FILES = {}  # output name -> generator; each generator registers itself below its definition


def config_hpp() -> str:
    out = [HEADER.format(src="data2g/config.py"), "#pragma once\n\n#include <array>\n#include <span>\n",
           "#include <string_view>\n\nnamespace data2g::config {\n\n"]
    for name, v in vars(config).items():
        if not name.isupper() or name.startswith("_") or name in SKIP:
            continue
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            out.append(f"inline constexpr {'double' if isinstance(v, float) else 'int'} {name} = {cxx(v)};\n")
        elif isinstance(v, tuple) and v:
            out.append(array(name, v, ctype_of(v)))
        else:
            sys.exit(f"config.{name}: no C++ form for {type(v).__name__}; emit it or add it to SKIP")
    out.append(f"inline constexpr double PREAMBLE_THRESHOLD = {cxx(config.PREAMBLE_THRESHOLDS[config.PREAMBLE_REPEATS])};\n")

    out.append("\nstruct Band {\n    std::string_view name;\n    int k0, nc;\n    std::span<const int> pilot_num;\n"
               "    int header_syms, preamble_repeats;\n    double clip_headroom_db;\n"
               "    std::span<const double> clip_overshoot;\n    std::string_view sync_band;\n};\n\n")
    for b in config.BANDS.values():
        out.append(array(f"PILOT_{b.name}", b.pilot_num, "int"))
        out.append(array(f"CLIP_OVERSHOOT_{b.name}", b.clip_overshoot, "double"))
    out.append(f"\ninline constexpr std::array<Band, {len(config.BANDS)}> BANDS = {{{{\n")
    for b in config.BANDS.values():
        out.append(f'    {{"{b.name}", {b.k0}, {b.nc}, PILOT_{b.name}, {b.header_syms}, {b.preamble_repeats}, '
                   f'{cxx(float(b.clip_headroom_db))}, CLIP_OVERSHOOT_{b.name}, "{b.sync_band}"}},\n')
    out.append("}};\n\n")

    out.append("// Per submode: the spec plus what Python derives from it, so the two\n"
               "// cannot disagree about sizes.\nstruct Submode {\n    int index;\n    std::string_view name, code, constellation, band, sync_band;\n"
               "    int frames_per_cw, k, bits_per_cu, coded_bits, crc_bits, payload_bytes;\n"
               "    double headroom;\n    std::span<const double> ace;\n};\n\n")
    subs = list(config.SUBMODES.values())
    for i, s in enumerate(subs):
        if s.ace:
            out.append(array(f"ACE_{i}", tuple(float(a) for a in s.ace), "double"))
    out.append(f"\ninline constexpr std::array<Submode, {len(subs)}> SUBMODES = {{{{\n")
    for i, s in enumerate(subs):
        ace = f"ACE_{i}" if s.ace else "{}"
        out.append(f'    {{{s.index}, "{s.name}", "{s.code}", "{s.constellation}", "{s.band}", "{s.sync_band}", '
                   f"{s.frames_per_cw}, {s.k}, {s.bits_per_cu}, {s.coded_bits}, {codes.crc_bits(s)}, "
                   f"{codes.payload_bytes(s)}, {cxx(float(s.headroom))}, {ace}}},\n")
    out.append("}};\n\n}  // namespace data2g::config\n")
    return "".join(out)


FILES["config.hpp"] = config_hpp


def ints(values) -> str:
    return ",".join(str(int(v)) for v in values)


def format_cpp() -> str:
    """Every submode's frozen interleaver and polar info set (data2g/format)."""
    out = [HEADER.format(src="data2g/format/*.npz"), '#include "tables/tables.hpp"\n\n',
           "namespace data2g::tables {\nnamespace {\n\n"]
    rows = []
    for i, s in enumerate(config.SUBMODES.values()):
        f = codes.frozen(s)
        if f is None:
            sys.exit(f"{s.name}: no frozen format file matches its spec; run tools/freeze_format.py first")
        perm = f["perm"]
        assert perm.max() < 65536 and sorted(perm) == list(range(s.coded_bits))
        out.append(f"constexpr std::uint16_t perm_{i}[] = {{{ints(perm)}}};\n")
        info = f"std::span<const std::uint16_t>{{}}"
        if "info_pos" in f:
            out.append(f"constexpr std::uint16_t info_{i}[] = {{{ints(f['info_pos'])}}};\n")
            info = f"info_{i}"
        rows.append(f'    {{"{s.name}", perm_{i}, {info}}},\n')
    out.append("\n}  // namespace\n\n")
    out.append(f"const std::array<Format, {len(rows)}> FORMATS = {{{{\n{''.join(rows)}}}}};\n\n}}  // namespace data2g::tables\n")
    return "".join(out)


FILES["format.cpp"] = format_cpp


def complexes(values) -> str:
    return ",".join(f"{{{float(v.real)!r},{float(v.imag)!r}}}" for v in values)


def constellation_cpp() -> str:
    """Every loadable constellation's points and frozen ACE directions
    (constellation.ace_dirs runs scipy's ConvexHull on learned sets)."""
    names = [f"gray-qam{4**k}" for k in range(1, 5)] + sorted(p.stem for p in constellation.DIR.glob("*.npy"))
    out = [HEADER.format(src="data2g/constellation.py, data2g/constellations/*.npy"),
           '#include "tables/tables.hpp"\n\n', "namespace data2g::tables {\nnamespace {\n\n"]
    rows = []
    for i, name in enumerate(names):
        pts, dirs = constellation.load(name), constellation.ace_dirs(name)
        m = constellation.bits_per_symbol(pts)
        assert pts.dtype == np.complex128 and len(pts) == 2**m and dirs.shape == (len(pts), 2)
        out.append(f"constexpr std::complex<double> points_{i}[] = {{{complexes(pts)}}};\n")
        out.append(f"constexpr std::complex<double> ace_{i}[] = {{{complexes(dirs.reshape(-1))}}};\n")
        rows.append(f'    {{"{name}", {m}, points_{i}, ace_{i}}},\n')
    out.append(f"\nconstexpr std::array<Constellation, {len(rows)}> TABLE = {{{{\n{''.join(rows)}}}}};\n\n"
               "}  // namespace\n\nconst std::span<const Constellation> CONSTELLATIONS = TABLE;\n\n"
               "}  // namespace data2g::tables\n")
    return "".join(out)


FILES["constellation.cpp"] = constellation_cpp


def cpm_cpp() -> str:
    """CPM grids, specs, and every on-air tone pattern: the sync blocks
    (Costas / Welch arrays) and the header tones, which data2g.cpm draws
    from numpy's PCG64 (frozen per grid for all 1024 header values, so no
    RNG is ported)."""
    from data2g import cpm, modem

    out = [HEADER.format(src="data2g/cpm.py"), '#include "tables/tables.hpp"\n\n',
           "namespace data2g::tables {\nnamespace {\n\n"]
    rows = []
    for i, g in enumerate(cpm.GRIDS.values()):
        assert g.m <= 256
        tones = [cpm.header_symbols(g.name, (v << 6) | modem._crc6(v)) for v in range(1024)]
        out.append(f"constexpr std::uint8_t pre_{i}[] = {{{ints(cpm.preamble_pattern(g))}}};\n")
        out.append(f"constexpr std::uint8_t mid_{i}[] = {{{ints(cpm.mid_block(g))}}};\n")
        out.append(f"constexpr std::uint8_t hdr_{i}[] = {{{ints(np.concatenate(tones))}}};\n")
        rows.append(f'    {{"{g.name}", {g.m}, {cxx(float(g.rate))}, {cxx(float(g.center))}, {cxx(float(g.bp))}, '
                    f"{cxx(float(g.clip_db))}, {g.T}, {g.bits}, {cxx(float(g.f0))}, "
                    f"{cxx(float(cpm.SYNC_THRESHOLD[g.name]))}, {cxx(float(cpm.HEADER_THRESHOLD[g.name]))}, "
                    f"{cpm.hdr_len(g)}, {len(cpm.costas(g.m))}, pre_{i}, mid_{i}, hdr_{i}}},\n")

    # interleavers: codes.compute_interleaver's PCG64 permutations (no format file)
    all_specs = [*cpm.SPECS.values(), *cpm.CTL.values()]
    for j, s in enumerate(all_specs):
        perm = codes.interleaver(s)
        assert sorted(perm) == list(range(s.coded_bits))
        out.append(f"constexpr std::uint16_t perm_{j}[] = {{{ints(perm)}}};\n")

    def spec(s):
        return (f'    {{"{s.name}", "{s.grid}", "{s.code}", {s.index}, {s.k}, {s.coded_bits}, {s.n_sym}, '
                f"perm_{all_specs.index(s)}}},\n")

    out.append(f"\nconstexpr CpmGrid grids[] = {{\n{''.join(rows)}}};\n")
    out.append(f"constexpr CpmSpec specs[] = {{\n{''.join(spec(s) for s in cpm.SPECS.values())}}};\n")
    out.append(f"constexpr CpmSpec ctl[] = {{\n{''.join(spec(cpm.CTL[g]) for g in cpm.GRIDS)}}};\n")
    out.append("\n}  // namespace\n\n")
    out.append("const std::span<const CpmGrid> CPM_GRIDS = grids;\nconst std::span<const CpmSpec> CPM_SPECS = specs;\n"
               "const std::span<const CpmSpec> CPM_CTL = ctl;\n")
    c = cpm
    out.append(f"const CpmParams CPM = {{{c.PREAMBLE_S!r}, {c.BLOCK_S!r}, {c.SPACING_S!r}, {c.HDR_S!r}, {c.HDR_COPIES}, "
               f"{c.MAX_DATA}, {c.PEAK_RATIO!r}, {c.RAMP_S!r}, {c.DATA_N}, {c.CTL_K}, {c.CTL_N}}};\n\n")
    out.append("}  // namespace data2g::tables\n")
    return "".join(out)


FILES["cpm.cpp"] = cpm_cpp


def polar_ga_cpp() -> str:
    """Polar info sets the live path designs at run time (GA density
    evolution at codes.POLAR_DESIGN_SNR_DB) because no frozen file holds
    one: the CPM control codewords. Keyed by (k, e)."""
    from data2g import cpm

    out = [HEADER.format(src="data2g/polar.py (codes.polar_code of cpm.CTL)"), '#include "tables/tables.hpp"\n\n',
           f"// Design SNR {cxx(float(codes.POLAR_DESIGN_SNR_DB))} dB.\n",
           "namespace data2g::tables {\nnamespace {\n\n"]
    rows, seen = [], set()
    for s in cpm.CTL.values():
        if s.code != "polar" or (s.k, s.coded_bits) in seen:
            continue
        code = codes.polar_code(s)
        assert code.frozen_override is None, f"{s.name} has a frozen info set; it doesn't belong here"
        seen.add((s.k, s.coded_bits))
        out.append(f"constexpr std::uint16_t ga_{len(rows)}[] = {{{ints(code.info_pos)}}};\n")
        rows.append(f"    {{{s.k}, {s.coded_bits}, ga_{len(rows)}}},\n")
    out.append(f"\nconstexpr PolarDesign designs[] = {{\n{''.join(rows)}}};\n\n}}  // namespace\n\n"
               "const std::span<const PolarDesign> POLAR_GA = designs;\n\n}  // namespace data2g::tables\n")
    return "".join(out)


FILES["polar_ga.cpp"] = polar_ga_cpp
# equalizer.per_carrier_noise's `samples`: a burst's pilot count (at most
# MAX_CODEWORDS * the longest codeword + a header-copy frame + the closing
# pilot) or 7 (preamble repeats). Tabulated past that; C++ throws outside.
GAMMA_Q99_MAX = 2048


def gamma_q99_cpp() -> str:
    """gamma.ppf(0.99, n) / n for n = 1..GAMMA_Q99_MAX (equalizer.py:176)."""
    from scipy.stats import gamma

    need = config.MAX_CODEWORDS * max(s.frames_per_cw for s in config.SUBMODES.values()) + 2
    assert need <= GAMMA_Q99_MAX, f"raise GAMMA_Q99_MAX to at least {need}"
    n = np.arange(1, GAMMA_Q99_MAX + 1)
    q = gamma.ppf(0.99, n) / n
    rows = ",\n".join(", ".join(repr(float(v)) for v in q[i:i + 4]) for i in range(0, len(q), 4))
    return (HEADER.format(src="scipy.stats.gamma") + '#include "tables/tables.hpp"\n\nnamespace data2g::tables {\n\n'
            f"const std::array<double, GAMMA_Q99_MAX> GAMMA_Q99 = {{{{\n{rows}}}}};\n\n}}  // namespace data2g::tables\n")


FILES["gamma_q99.cpp"] = gamma_q99_cpp
def ldpc_cpp() -> str:
    """Every QC-LDPC shift table (data2g/codes_data/ldpc_shifts.npz)."""
    from data2g import ldpc

    out = [HEADER.format(src="data2g/codes_data/ldpc_shifts.npz"), '#include "tables/tables.hpp"\n\n',
           "namespace data2g::tables {\nnamespace {\n\n"]
    rows = []
    for key, base in ldpc.tables().items():
        if key.startswith("mask"):
            continue  # the mask is base >= 0
        bg, z = (int(v.lstrip("bgz")) for v in key.split("_"))
        assert base.min() >= -1 and base.max() < z
        out.append(f"constexpr std::int16_t {key}[] = {{{ints(base.reshape(-1))}}};\n")
        rows.append(f"    {{{bg}, {z}, {base.shape[0]}, {base.shape[1]}, {key}}},\n")
    out.append(f"\nconstexpr ShiftTable shifts[] = {{\n{''.join(rows)}}};\n\n}}  // namespace\n\n")
    out.append("const std::span<const ShiftTable> LDPC_SHIFTS = shifts;\n\n}  // namespace data2g::tables\n")
    return "".join(out)


FILES["ldpc.cpp"] = ldpc_cpp


def doubles(values) -> str:
    return ",\n".join(", ".join(repr(float(v)) for v in values[i:i + 6]) for i in range(0, len(values), 6))


def predictor_cpp() -> str:
    """The gear shifter's outcome model (codes_data/outcome_predictor.npz,
    the installed ensemble; DATA2G_OUTCOME_MODEL is study-only) and the AWGN
    BICM capacity tables its MI features interpolate (capacity_tables.npz)."""
    from data2g.arq import predictor as P

    model = P.outcome_model(str(P.DATA / "outcome_predictor.npz"))
    members = model.members if isinstance(model, P.OutcomeEnsemble) else [model]
    out = [HEADER.format(src="data2g/codes_data/{outcome_predictor,capacity_tables}.npz"),
           '#include "tables/tables.hpp"\n\n', "namespace data2g::tables {\nnamespace {\n\n"]
    rows = []
    for i, m in enumerate(members):
        assert m.modes == model.modes and m.bands == model.bands
        out.append(f"constexpr double mean_{i}[] = {{\n{doubles(m.mean)}}};\n")
        out.append(f"constexpr double std_{i}[] = {{\n{doubles(m.std)}}};\n")
        layers = []
        for j, (w, b) in enumerate(m.layers):
            assert w.dtype == b.dtype == np.float64 and w.shape[1] == b.shape[0]
            out.append(f"constexpr double w_{i}_{j}[] = {{\n{doubles(w.reshape(-1))}}};\n")
            out.append(f"constexpr double b_{i}_{j}[] = {{\n{doubles(b)}}};\n")
            layers.append(f"{{{w.shape[0]}, {w.shape[1]}, w_{i}_{j}, b_{i}_{j}}}")
        out.append(f"constexpr MlpLayer layers_{i}[] = {{{', '.join(layers)}}};\n\n")
        rows.append(f"    {{mean_{i}, std_{i}, layers_{i}}},\n")
    out.append(f"constexpr OutcomeMember members[] = {{\n{''.join(rows)}}};\n")
    out.append(f"constexpr std::string_view modes[] = {{{', '.join(cxx(m) for m in model.modes)}}};\n")
    out.append(f"constexpr std::string_view bands[] = {{{', '.join(cxx(b) for b in model.bands)}}};\n\n")
    grid, tables = P._capacity()
    out.append(f"constexpr double grid[] = {{\n{doubles(grid)}}};\n")
    for i, c in enumerate(P.CONSTS):
        assert len(tables[c]) == len(grid)
        out.append(f"constexpr double cap_{i}[] = {{\n{doubles(tables[c])}}};\n")
    caps = ", ".join(f"{{{cxx(c)}, cap_{i}}}" for i, c in enumerate(P.CONSTS))
    out.append(f"constexpr CapacityTable caps[] = {{{caps}}};\n\n}}  // namespace\n\n")
    out.append("const std::span<const OutcomeMember> OUTCOME_MEMBERS = members;\n"
               "const std::span<const std::string_view> OUTCOME_MODES = modes;\n"
               "const std::span<const std::string_view> OUTCOME_BANDS = bands;\n"
               "const std::span<const double> CAPACITY_GRID = grid;\n"
               "const std::span<const CapacityTable> CAPACITY = caps;\n\n}  // namespace data2g::tables\n")
    return "".join(out)


FILES["predictor.cpp"] = predictor_cpp


def modem_hpp() -> str:
    """data2g/modem.py's constants, header codes and the clip constants its
    receiver reads (config.clip_consts, from clip_constants.json). A header
    code (16, N) is emitted as N 16-bit column masks: coded bit j of word w
    is the parity of w & col[j] (bit 15 = the code's row 0)."""
    from data2g import modem

    out = [HEADER.format(src="data2g/modem.py, data2g/codes_data/{header_code*.npy,clip_constants.json}"),
           "#pragma once\n\n#include <array>\n#include <cstdint>\n#include <span>\n#include <string_view>\n"
           "#include <utility>\n\nnamespace data2g::modem {\n\n"]
    for name in ("REF_REPEATS", "HEADER_BACKOFF", "STREAM_COMMIT_SCORE", "COPY_COMMIT_SCORE", "ALT_PENALTY",
                 "PILOT_PAIRS", "COPY_PAIRS", "COPY_GRIDS", "COPY_COHERENCE", "COPY_DETECT"):
        v = getattr(modem, name)
        out.append(f"inline constexpr {'double' if isinstance(v, float) else 'int'} {name} = {cxx(v)};\n")
    out.append(array("COPY_EARLIER", modem.COPY_EARLIER, "int"))
    out.append(array("SYNC_BANDS", modem.SYNC_BANDS, "std::string_view"))

    def per_band(name, d):
        rows = ", ".join(f'{{"{b}", {cxx(float(v))}}}' for b, v in d.items())
        return (f"inline constexpr std::array<std::pair<std::string_view, double>, {len(d)}> {name} = "
                f"{{{{{rows}}}}};\n")

    out.append(per_band("HEADER_MIN_SCORE", modem.HEADER_MIN_SCORE))
    out.append(per_band("PILOT_NOISE", modem.PILOT_NOISE))

    out.append("\n// Header codes per sync band, as column masks.\n")
    rows = []
    for b in modem.SYNC_BANDS:
        g = modem.header_code(b)
        cols = [sum(int(g[r, j]) << (15 - r) for r in range(16)) for j in range(g.shape[1])]
        out.append(array(f"HEADER_COLS_{b}", cols, "std::uint16_t"))
        rows.append(f'{{"{b}", HEADER_COLS_{b}}}')
    out.append(f"inline constexpr std::array<std::pair<std::string_view, std::span<const std::uint16_t>>, "
               f"{len(rows)}> HEADER_CODES = {{{{{', '.join(rows)}}}}};\n")

    out.append("\n// config.clip_consts: (gain of a 1-frame burst, any other burst's, clip-noise ratio).\n"
               "struct Clip {\n    double gain_1f, gain, ratio;\n};\n")

    def clip(c):
        gains, default, ratio = c
        assert list(gains) == [1]
        return f"{{{cxx(float(gains[1]))}, {cxx(float(default))}, {cxx(float(ratio))}}}"

    subs = [clip(config.clip_consts(s.band, s.headroom, s.ace, s.constellation)) for s in config.SUBMODES.values()]
    out.append(f"// receive()'s, per config::SUBMODES row\ninline constexpr std::array<Clip, {len(subs)}> CLIP_SUBMODE = "
               f"{{{{\n    {', '.join(subs)}}}}};\n")
    bands = [clip(config.CLIP[b]) for b in config.BANDS]
    out.append(f"// config.CLIP, per config::BANDS row\ninline constexpr std::array<Clip, {len(bands)}> CLIP_BAND = "
               f"{{{{{', '.join(bands)}}}}};\n")
    out.append("\n}  // namespace data2g::modem\n")
    return "".join(out)


FILES["modem.hpp"] = modem_hpp


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="compare, write nothing")
    args = ap.parse_args()
    stale = []
    for name, gen in FILES.items():
        path, text = OUT / name, gen()
        if args.check:
            if not path.exists() or path.read_bytes() != text.encode():
                stale.append(name)
        else:
            OUT.mkdir(parents=True, exist_ok=True)
            path.write_bytes(text.encode())
    if stale:
        sys.exit(f"stale: {', '.join(stale)} (run tools/gen_native_tables.py)")


if __name__ == "__main__":
    main()
